<?php
$data = array (
  0 => 
  array (
    'cat_id' => '4',
    'cat_name' => '家居/厨具',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '1',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  1 => 
  array (
    'cat_id' => '5',
    'cat_name' => '家居生活',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '2',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  2 => 
  array (
    'cat_id' => '6',
    'cat_name' => '服装配饰',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '3',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  3 => 
  array (
    'cat_id' => '7',
    'cat_name' => '礼品箱包',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '4',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  4 => 
  array (
    'cat_id' => '8',
    'cat_name' => '数码办公',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '5',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  5 => 
  array (
    'cat_id' => '9',
    'cat_name' => '茶叶酒水',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '6',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  6 => 
  array (
    'cat_id' => '10',
    'cat_name' => '母婴用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  7 => 
  array (
    'cat_id' => '11',
    'cat_name' => '汽车用品',
    'measure_unit' => '',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '7',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  8 => 
  array (
    'cat_id' => '1',
    'cat_name' => '手机类型',
    'measure_unit' => '部',
    'parent_id' => '0',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  9 => 
  array (
    'cat_id' => '3',
    'cat_name' => '智能机',
    'measure_unit' => '部',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  10 => 
  array (
    'cat_id' => '2',
    'cat_name' => '功能机',
    'measure_unit' => '部',
    'parent_id' => '1',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  11 => 
  array (
    'cat_id' => '12',
    'cat_name' => '面部护肤',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  12 => 
  array (
    'cat_id' => '13',
    'cat_name' => '女性护理',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  13 => 
  array (
    'cat_id' => '14',
    'cat_name' => '男士护理',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  14 => 
  array (
    'cat_id' => '15',
    'cat_name' => '个人护理',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  15 => 
  array (
    'cat_id' => '16',
    'cat_name' => '魅力彩妆',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  16 => 
  array (
    'cat_id' => '17',
    'cat_name' => '精油芳疗',
    'measure_unit' => '',
    'parent_id' => '4',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '60',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  17 => 
  array (
    'cat_id' => '18',
    'cat_name' => '厨具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  18 => 
  array (
    'cat_id' => '19',
    'cat_name' => '家具',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  19 => 
  array (
    'cat_id' => '20',
    'cat_name' => '小家电',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  20 => 
  array (
    'cat_id' => '21',
    'cat_name' => '家纺',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  21 => 
  array (
    'cat_id' => '22',
    'cat_name' => '生活日用',
    'measure_unit' => '',
    'parent_id' => '5',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  22 => 
  array (
    'cat_id' => '23',
    'cat_name' => '内衣',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  23 => 
  array (
    'cat_id' => '24',
    'cat_name' => '配饰',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  24 => 
  array (
    'cat_id' => '25',
    'cat_name' => '首饰',
    'measure_unit' => '',
    'parent_id' => '6',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  25 => 
  array (
    'cat_id' => '26',
    'cat_name' => '礼品',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  26 => 
  array (
    'cat_id' => '27',
    'cat_name' => '婚庆',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  27 => 
  array (
    'cat_id' => '28',
    'cat_name' => '精品女包',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  28 => 
  array (
    'cat_id' => '29',
    'cat_name' => '时尚男包',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  29 => 
  array (
    'cat_id' => '30',
    'cat_name' => '功能箱包',
    'measure_unit' => '',
    'parent_id' => '7',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  30 => 
  array (
    'cat_id' => '31',
    'cat_name' => '手机配件',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  31 => 
  array (
    'cat_id' => '32',
    'cat_name' => '电脑配件',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  32 => 
  array (
    'cat_id' => '33',
    'cat_name' => '数码配件',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  33 => 
  array (
    'cat_id' => '34',
    'cat_name' => '办公用品',
    'measure_unit' => '',
    'parent_id' => '8',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  34 => 
  array (
    'cat_id' => '35',
    'cat_name' => '茶叶冲调',
    'measure_unit' => '1',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  35 => 
  array (
    'cat_id' => '36',
    'cat_name' => '酒水饮料',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  36 => 
  array (
    'cat_id' => '37',
    'cat_name' => '休闲零食',
    'measure_unit' => '',
    'parent_id' => '9',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  37 => 
  array (
    'cat_id' => '38',
    'cat_name' => '婴儿用品',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '5',
    'goods_num' => 0,
  ),
  38 => 
  array (
    'cat_id' => '39',
    'cat_name' => '孕妈专区',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  39 => 
  array (
    'cat_id' => '40',
    'cat_name' => '宝宝洗护',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  40 => 
  array (
    'cat_id' => '41',
    'cat_name' => '喂养用品',
    'measure_unit' => '',
    'parent_id' => '10',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '3',
    'goods_num' => 0,
  ),
  41 => 
  array (
    'cat_id' => '42',
    'cat_name' => '汽车美容',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '10',
    'has_children' => '4',
    'goods_num' => 0,
  ),
  42 => 
  array (
    'cat_id' => '43',
    'cat_name' => '汽车配件',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '20',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  43 => 
  array (
    'cat_id' => '44',
    'cat_name' => '精品车饰',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '30',
    'has_children' => '6',
    'goods_num' => 0,
  ),
  44 => 
  array (
    'cat_id' => '45',
    'cat_name' => 'GPS导航',
    'measure_unit' => '',
    'parent_id' => '11',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '40',
    'has_children' => '2',
    'goods_num' => 0,
  ),
  45 => 
  array (
    'cat_id' => '46',
    'cat_name' => '洁面乳',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  46 => 
  array (
    'cat_id' => '47',
    'cat_name' => '面膜',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  47 => 
  array (
    'cat_id' => '48',
    'cat_name' => '面霜',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  48 => 
  array (
    'cat_id' => '49',
    'cat_name' => '爽肤水',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  49 => 
  array (
    'cat_id' => '50',
    'cat_name' => '护理套装',
    'measure_unit' => '',
    'parent_id' => '12',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  50 => 
  array (
    'cat_id' => '51',
    'cat_name' => '洗液',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  51 => 
  array (
    'cat_id' => '52',
    'cat_name' => '美容品',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  52 => 
  array (
    'cat_id' => '53',
    'cat_name' => '香水',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  53 => 
  array (
    'cat_id' => '54',
    'cat_name' => '化妆品',
    'measure_unit' => '',
    'parent_id' => '13',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  54 => 
  array (
    'cat_id' => '55',
    'cat_name' => '洁面',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  55 => 
  array (
    'cat_id' => '56',
    'cat_name' => '剃须',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  56 => 
  array (
    'cat_id' => '57',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  57 => 
  array (
    'cat_id' => '58',
    'cat_name' => '香水',
    'measure_unit' => '',
    'parent_id' => '14',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  58 => 
  array (
    'cat_id' => '59',
    'cat_name' => '洗发水',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  59 => 
  array (
    'cat_id' => '60',
    'cat_name' => '沐浴露',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  60 => 
  array (
    'cat_id' => '61',
    'cat_name' => '香皂',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  61 => 
  array (
    'cat_id' => '62',
    'cat_name' => '牙膏牙刷',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  62 => 
  array (
    'cat_id' => '63',
    'cat_name' => '啫喱',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  63 => 
  array (
    'cat_id' => '64',
    'cat_name' => '花露水',
    'measure_unit' => '',
    'parent_id' => '15',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '160',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  64 => 
  array (
    'cat_id' => '65',
    'cat_name' => '粉底',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  65 => 
  array (
    'cat_id' => '66',
    'cat_name' => '眼线',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  66 => 
  array (
    'cat_id' => '67',
    'cat_name' => '睫毛膏',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  67 => 
  array (
    'cat_id' => '68',
    'cat_name' => '唇彩',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  68 => 
  array (
    'cat_id' => '69',
    'cat_name' => '唇膏',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  69 => 
  array (
    'cat_id' => '70',
    'cat_name' => '眼影',
    'measure_unit' => '',
    'parent_id' => '16',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '160',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  70 => 
  array (
    'cat_id' => '71',
    'cat_name' => '单方精油',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  71 => 
  array (
    'cat_id' => '72',
    'cat_name' => '复方精油',
    'measure_unit' => '',
    'parent_id' => '17',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  72 => 
  array (
    'cat_id' => '73',
    'cat_name' => '烹饪锅具',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  73 => 
  array (
    'cat_id' => '74',
    'cat_name' => '刀剪砧板',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  74 => 
  array (
    'cat_id' => '75',
    'cat_name' => '收纳保鲜',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  75 => 
  array (
    'cat_id' => '76',
    'cat_name' => '水具酒具',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  76 => 
  array (
    'cat_id' => '77',
    'cat_name' => '餐具',
    'measure_unit' => '',
    'parent_id' => '18',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  77 => 
  array (
    'cat_id' => '78',
    'cat_name' => '床',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  78 => 
  array (
    'cat_id' => '79',
    'cat_name' => '沙发',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  79 => 
  array (
    'cat_id' => '80',
    'cat_name' => '餐桌餐椅',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  80 => 
  array (
    'cat_id' => '81',
    'cat_name' => '茶几',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  81 => 
  array (
    'cat_id' => '82',
    'cat_name' => '柜子',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  82 => 
  array (
    'cat_id' => '83',
    'cat_name' => '办公类',
    'measure_unit' => '',
    'parent_id' => '19',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '160',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  83 => 
  array (
    'cat_id' => '84',
    'cat_name' => '剃须刀',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  84 => 
  array (
    'cat_id' => '85',
    'cat_name' => '电吹风',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  85 => 
  array (
    'cat_id' => '86',
    'cat_name' => '小电扇',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  86 => 
  array (
    'cat_id' => '87',
    'cat_name' => '按摩器',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  87 => 
  array (
    'cat_id' => '88',
    'cat_name' => '电熨斗',
    'measure_unit' => '',
    'parent_id' => '20',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  88 => 
  array (
    'cat_id' => '90',
    'cat_name' => '床上用品',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  89 => 
  array (
    'cat_id' => '91',
    'cat_name' => '被子',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  90 => 
  array (
    'cat_id' => '92',
    'cat_name' => '枕头',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  91 => 
  array (
    'cat_id' => '93',
    'cat_name' => '毛巾',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  92 => 
  array (
    'cat_id' => '94',
    'cat_name' => '床垫',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  93 => 
  array (
    'cat_id' => '95',
    'cat_name' => '抱枕',
    'measure_unit' => '',
    'parent_id' => '21',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '160',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  94 => 
  array (
    'cat_id' => '89',
    'cat_name' => '收纳用品',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  95 => 
  array (
    'cat_id' => '96',
    'cat_name' => '洗晒用品',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  96 => 
  array (
    'cat_id' => '97',
    'cat_name' => '浴室用品',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  97 => 
  array (
    'cat_id' => '98',
    'cat_name' => '净化除味',
    'measure_unit' => '',
    'parent_id' => '22',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  98 => 
  array (
    'cat_id' => '101',
    'cat_name' => '丝袜',
    'measure_unit' => '130',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '50',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  99 => 
  array (
    'cat_id' => '99',
    'cat_name' => '文胸',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  100 => 
  array (
    'cat_id' => '100',
    'cat_name' => '内裤',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  101 => 
  array (
    'cat_id' => '102',
    'cat_name' => '棉袜',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  102 => 
  array (
    'cat_id' => '103',
    'cat_name' => '睡衣',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  103 => 
  array (
    'cat_id' => '104',
    'cat_name' => '保暖衣',
    'measure_unit' => '',
    'parent_id' => '23',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '160',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  104 => 
  array (
    'cat_id' => '105',
    'cat_name' => '腰带',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  105 => 
  array (
    'cat_id' => '106',
    'cat_name' => '丝巾',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  106 => 
  array (
    'cat_id' => '107',
    'cat_name' => '帽子',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  107 => 
  array (
    'cat_id' => '108',
    'cat_name' => '围巾',
    'measure_unit' => '',
    'parent_id' => '24',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  108 => 
  array (
    'cat_id' => '109',
    'cat_name' => '项链',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  109 => 
  array (
    'cat_id' => '110',
    'cat_name' => '戒指',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  110 => 
  array (
    'cat_id' => '111',
    'cat_name' => '手链',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  111 => 
  array (
    'cat_id' => '112',
    'cat_name' => '耳钉',
    'measure_unit' => '',
    'parent_id' => '25',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  112 => 
  array (
    'cat_id' => '113',
    'cat_name' => '礼品文具',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  113 => 
  array (
    'cat_id' => '114',
    'cat_name' => '收藏品',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  114 => 
  array (
    'cat_id' => '115',
    'cat_name' => '创意礼品',
    'measure_unit' => '',
    'parent_id' => '26',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  115 => 
  array (
    'cat_id' => '116',
    'cat_name' => '婚庆礼品',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  116 => 
  array (
    'cat_id' => '117',
    'cat_name' => '婚庆用品',
    'measure_unit' => '',
    'parent_id' => '27',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  117 => 
  array (
    'cat_id' => '118',
    'cat_name' => '单肩包',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  118 => 
  array (
    'cat_id' => '119',
    'cat_name' => '双肩包',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  119 => 
  array (
    'cat_id' => '120',
    'cat_name' => '手提包',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  120 => 
  array (
    'cat_id' => '121',
    'cat_name' => '斜挎包',
    'measure_unit' => '',
    'parent_id' => '28',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  121 => 
  array (
    'cat_id' => '122',
    'cat_name' => '商务包',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  122 => 
  array (
    'cat_id' => '123',
    'cat_name' => '休闲包',
    'measure_unit' => '',
    'parent_id' => '29',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  123 => 
  array (
    'cat_id' => '124',
    'cat_name' => '电脑包',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  124 => 
  array (
    'cat_id' => '125',
    'cat_name' => '拉杆箱',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  125 => 
  array (
    'cat_id' => '126',
    'cat_name' => '书包',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  126 => 
  array (
    'cat_id' => '127',
    'cat_name' => '钱包',
    'measure_unit' => '',
    'parent_id' => '30',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  127 => 
  array (
    'cat_id' => '128',
    'cat_name' => '手机壳',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  128 => 
  array (
    'cat_id' => '129',
    'cat_name' => '手机饰品',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  129 => 
  array (
    'cat_id' => '130',
    'cat_name' => '内存卡',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  130 => 
  array (
    'cat_id' => '131',
    'cat_name' => '耳机',
    'measure_unit' => '',
    'parent_id' => '31',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  131 => 
  array (
    'cat_id' => '132',
    'cat_name' => '散热器',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  132 => 
  array (
    'cat_id' => '133',
    'cat_name' => '内存卡',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  133 => 
  array (
    'cat_id' => '134',
    'cat_name' => '清洁工具',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  134 => 
  array (
    'cat_id' => '135',
    'cat_name' => '电脑耳机',
    'measure_unit' => '',
    'parent_id' => '32',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  135 => 
  array (
    'cat_id' => '136',
    'cat_name' => '内存卡',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  136 => 
  array (
    'cat_id' => '137',
    'cat_name' => '读卡器',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  137 => 
  array (
    'cat_id' => '138',
    'cat_name' => '移动电源',
    'measure_unit' => '',
    'parent_id' => '33',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  138 => 
  array (
    'cat_id' => '139',
    'cat_name' => '钢笔',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  139 => 
  array (
    'cat_id' => '140',
    'cat_name' => '中性笔',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  140 => 
  array (
    'cat_id' => '141',
    'cat_name' => '计算器',
    'measure_unit' => '',
    'parent_id' => '34',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  141 => 
  array (
    'cat_id' => '142',
    'cat_name' => '茶刀',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  142 => 
  array (
    'cat_id' => '143',
    'cat_name' => '茶具',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  143 => 
  array (
    'cat_id' => '144',
    'cat_name' => '茶叶',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  144 => 
  array (
    'cat_id' => '145',
    'cat_name' => '茶饼',
    'measure_unit' => '',
    'parent_id' => '35',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  145 => 
  array (
    'cat_id' => '146',
    'cat_name' => '红酒',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  146 => 
  array (
    'cat_id' => '147',
    'cat_name' => '白酒',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  147 => 
  array (
    'cat_id' => '148',
    'cat_name' => '朗姆酒',
    'measure_unit' => '',
    'parent_id' => '36',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  148 => 
  array (
    'cat_id' => '149',
    'cat_name' => '营养滋补',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  149 => 
  array (
    'cat_id' => '150',
    'cat_name' => '喜德旺',
    'measure_unit' => '',
    'parent_id' => '37',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  150 => 
  array (
    'cat_id' => '151',
    'cat_name' => '婴侍卫',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  151 => 
  array (
    'cat_id' => '152',
    'cat_name' => '沐浴',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => '1',
  ),
  152 => 
  array (
    'cat_id' => '153',
    'cat_name' => '理发',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  153 => 
  array (
    'cat_id' => '154',
    'cat_name' => '玩具',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  154 => 
  array (
    'cat_id' => '155',
    'cat_name' => '吸鼻器',
    'measure_unit' => '',
    'parent_id' => '38',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  155 => 
  array (
    'cat_id' => '156',
    'cat_name' => '妈妈护理',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  156 => 
  array (
    'cat_id' => '157',
    'cat_name' => '产后塑身',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  157 => 
  array (
    'cat_id' => '158',
    'cat_name' => '家居服',
    'measure_unit' => '',
    'parent_id' => '39',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  158 => 
  array (
    'cat_id' => '159',
    'cat_name' => '洗发露',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  159 => 
  array (
    'cat_id' => '160',
    'cat_name' => '沐浴露',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  160 => 
  array (
    'cat_id' => '161',
    'cat_name' => '洗浴用品',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  161 => 
  array (
    'cat_id' => '162',
    'cat_name' => '宝宝护肤',
    'measure_unit' => '',
    'parent_id' => '40',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  162 => 
  array (
    'cat_id' => '163',
    'cat_name' => '奶瓶',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  163 => 
  array (
    'cat_id' => '164',
    'cat_name' => '奶嘴',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  164 => 
  array (
    'cat_id' => '165',
    'cat_name' => '吸奶器',
    'measure_unit' => '',
    'parent_id' => '41',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  165 => 
  array (
    'cat_id' => '166',
    'cat_name' => '美容车蜡',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  166 => 
  array (
    'cat_id' => '167',
    'cat_name' => '洗车工具',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  167 => 
  array (
    'cat_id' => '168',
    'cat_name' => '擦车巾',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  168 => 
  array (
    'cat_id' => '169',
    'cat_name' => '海绵',
    'measure_unit' => '',
    'parent_id' => '42',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  169 => 
  array (
    'cat_id' => '170',
    'cat_name' => '雨敌',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  170 => 
  array (
    'cat_id' => '171',
    'cat_name' => '雨刷',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  171 => 
  array (
    'cat_id' => '172',
    'cat_name' => '打气泵',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  172 => 
  array (
    'cat_id' => '173',
    'cat_name' => '车垫脚垫',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  173 => 
  array (
    'cat_id' => '174',
    'cat_name' => '充电器',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  174 => 
  array (
    'cat_id' => '175',
    'cat_name' => '车钥匙扣',
    'measure_unit' => '',
    'parent_id' => '43',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '160',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  175 => 
  array (
    'cat_id' => '176',
    'cat_name' => '香水',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  176 => 
  array (
    'cat_id' => '177',
    'cat_name' => '方向盘套',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  177 => 
  array (
    'cat_id' => '178',
    'cat_name' => '装饰布艺',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '130',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  178 => 
  array (
    'cat_id' => '179',
    'cat_name' => '净化空气',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '140',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  179 => 
  array (
    'cat_id' => '180',
    'cat_name' => '3M胶',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '150',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  180 => 
  array (
    'cat_id' => '181',
    'cat_name' => '收纳用品',
    'measure_unit' => '',
    'parent_id' => '44',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '160',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  181 => 
  array (
    'cat_id' => '182',
    'cat_name' => 'E导游',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '110',
    'has_children' => '0',
    'goods_num' => 0,
  ),
  182 => 
  array (
    'cat_id' => '183',
    'cat_name' => '凯立德',
    'measure_unit' => '',
    'parent_id' => '45',
    'is_show' => '1',
    'show_in_nav' => '0',
    'grade' => '0',
    'sort_order' => '120',
    'has_children' => '0',
    'goods_num' => 0,
  ),
);
?>